--SNOWFLAKE MODEL--
CREATE TABLE CLIENT
(
    clientId number(10, 0) NOT NULL,
    nif      number(9, 0)  NOT NULL CHECK ( REGEXP_LIKE(nif, '^[1-4]\d{8}') ),
    PRIMARY KEY (clientId)
);
CREATE TABLE PRODUCT
(
    productId NUMBER(10, 0) NOT NULL,
    type      VARCHAR2(255) NOT NULL,
    name      VARCHAR2(255) NOT NULL,
    PRIMARY KEY (productId)
);
CREATE TABLE PRODUCTNAME
(
    name VARCHAR2(255) NOT NULL PRIMARY KEY
);
CREATE TABLE PRODUCTTYPE
(
    type VARCHAR2(255) NOT NULL PRIMARY KEY
);
CREATE TABLE PRODUCTION
(
    productionId NUMBER(10, 0) NOT NULL,
    timeId       NUMBER(10, 0) NOT NULL,
    sectorId     NUMBER(10, 0) NOT NULL,
    productId    NUMBER(10, 0) NOT NULL,
    amount       NUMBER(10, 0) NOT NULL,
    PRIMARY KEY (productId)
);
CREATE TABLE SALE
(
    saleId    NUMBER(10, 0) NOT NULL,
    timeId    NUMBER(10, 0) NOT NULL,
    clientId  NUMBER(10, 0) NOT NULL,
    productId NUMBER(10, 0) NOT NULL,
    quantity  NUMBER(10, 0) NOT NULL,
    PRIMARY KEY (saleId)
);
CREATE TABLE SECTOR
(
    sectorId    NUMBER(10, 0) NOT NULL,
    name        NUMBER(10, 0) NOT NULL,
    exploration NUMBER(10, 0) NOT NULL,
    PRIMARY KEY (sectorId)
);
CREATE TABLE TIME
(
    timeId NUMBER(10, 0) NOT NULL,
    year   NUMBER(4, 0)  NOT NULL,
    month  NUMBER(2, 0)  NOT NULL CHECK ( month BETWEEN 1 AND 12)
);
CREATE TABLE MONTH
(
    month NUMBER(4) NOT NULL CHECK ( month BETWEEN 1 AND 12) PRIMARY KEY
);
CREATE TABLE YEAR
(
    year NUMBER(4) NOT NULL PRIMARY KEY
);

ALTER TABLE PRODUCT
    ADD CONSTRAINT FKProductNameId FOREIGN KEY (name) REFERENCES PRODUCTNAME (name);
ALTER TABLE PRODUCT
    ADD CONSTRAINT FKProductTypeId FOREIGN KEY (type) REFERENCES PRODUCTTYPE (type);

ALTER TABLE PRODUCTION
    ADD CONSTRAINT FKProductionSectorId FOREIGN KEY (productionId) REFERENCES SECTOR (sectorId);
ALTER TABLE PRODUCTION
    ADD CONSTRAINT FKProductionProductId FOREIGN KEY (productId) REFERENCES PRODUCT (productId);
ALTER TABLE PRODUCTION
    ADD CONSTRAINT FKProductionTimeId FOREIGN KEY (timeId) REFERENCES TIME (timeId);


ALTER TABLE SALE
    ADD CONSTRAINT FKSaleClientId FOREIGN KEY (clientId) REFERENCES CLIENT (clientId);
ALTER TABLE SALE
    ADD CONSTRAINT FKSaleProductId FOREIGN KEY (productId) REFERENCES PRODUCT (productId);
ALTER TABLE SALE
    ADD CONSTRAINT FKSaleTimeId FOREIGN KEY (timeId) REFERENCES TIME (timeId);

ALTER TABLE TIME
    ADD CONSTRAINT FKTimeMonthId FOREIGN KEY (month) REFERENCES MONTH (month);
ALTER TABLE TIME
    ADD CONSTRAINT FKTimeYearId FOREIGN KEY (year) REFERENCES YEAR (year);


