SELECT *
FROM LastFiveYearsEvolution Parent
WHERE SECTORID = 1
  AND Name = 'Carrot'
ORDER BY YEAR, MONTH ASC;

SELECT MONTH, PRODUCT_NAME, FIRST_YEAR_SALES, YEARS_COMPARISON
FROM CompareSales
WHERE FIRST_YEAR = 2018
  AND SECOND_YEAR = 2017;

SELECT *
FROM MENSALEVOLUTIONOFCULTURETYPES;