CREATE OR REPLACE TRIGGER trgCreateMeteorologicStation
    BEFORE INSERT
    ON SECTOR
    FOR EACH ROW WHEN ( new.METEOROLOGICSTATION is NULL )
DECLARE
    stationId SECTOR.METEOROLOGICSTATION%type;
BEGIN
        INSERT INTO METEOROLOGICSTATION(NAME) VALUES ('Station');
        SELECT ID into stationId FROM METEOROLOGICSTATION ORDER BY ID DESC FETCH FIRST ROW ONLY;
        :new.METEOROLOGICSTATION := stationId;
end;