--CLEAN DATABASE DEPRECATED--
--First Phase--
DELETE AuditLog;
DELETE BasketOrder;
DELETE BasketProduct;
DELETE Building;
DELETE Client;
DELETE CropWatering;
DELETE CulturePlan;
DELETE DistributionManager;
DELETE Driver;
DELETE ExplorationClientele;
DELETE FarmingManager;
DELETE PRODUCTIONFACTORSRECORDING;
DELETE Harvest;
DELETE Hub;
DELETE input_sensor;
DELETE ReadingErrors;
DELETE MachineryGarage;
DELETE MeteorologicData;
DELETE ProductionEntry;
DELETE ProductionFactors;
DELETE ProductionZones;
DELETE Sector;
DELETE SensorReading;
DELETE Silos;
DELETE SprinklingSystem;
DELETE Stable;
DELETE SystemUser;
DELETE TubularSystem;
DELETE Valve;
--Second Phase--
DELETE Address;
DELETE Basket;
DELETE FieldRecording;
DELETE Sensor;
DELETE MeteorologicStation;
DELETE Product;
DELETE Exploration;
