INSERT INTO SYSTEMUSER(EMAIL, PASSWORD)
VALUES ('system@system.sys', 'qwerty123');

INSERT INTO EXPLORATION(ADDRESS) VALUES(null);

INSERT INTO PRODUCT(NAME, TYPE) VALUES('Carrot','TEMPORARY');
INSERT INTO PRODUCT(NAME, TYPE) VALUES('Apple','PERMANENT');
INSERT INTO PRODUCT(NAME, TYPE) VALUES('Bees', 'TEMPORARY');
INSERT INTO PRODUCT(NAME, TYPE) VALUES('Pears','PERMANENT');






DECLARE
    val NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Data Report:');
    FOR I IN (SELECT TABLE_NAME FROM USER_TABLES)
        LOOP
            EXECUTE IMMEDIATE 'SELECT count(*) FROM ' || i.table_name INTO val;
            DBMS_OUTPUT.PUT_LINE(i.table_name || ' ==> ' || val);
        END LOOP;
END;