INSERT INTO SYSTEMUSER(EMAIL, PASSWORD)
VALUES ('system@system.sys', 'qwerty123');

INSERT INTO EXPLORATION(ADDRESS) VALUES(null);

INSERT INTO FIELDRECORDING VALUES(1);

INSERT INTO PRODUCT(NAME, TYPE) VALUES('Carrot','TEMPORARY');
INSERT INTO PRODUCT(NAME, TYPE) VALUES('Apple','PERMANENT');
INSERT INTO PRODUCT(NAME, TYPE) VALUES('Bees', 'TEMPORARY');
INSERT INTO PRODUCT(NAME, TYPE) VALUES('Pears','PERMANENT');

INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(SYSDATE,3,100);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('8/10/2022','DD/MM/YYYY'),3,8);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('10/10/2022','DD/MM/YYYY'),3,30);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('9/10/2022','DD/MM/YYYY'),3,87);

INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(SYSDATE,4,1000);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('8/10/2022','DD/MM/YYYY'),4,80);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('10/10/2022','DD/MM/YYYY'),4,300);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('9/10/2022','DD/MM/YYYY'),4,870);

INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(SYSDATE,5,100);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('8/10/2022','DD/MM/YYYY'),5,8);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('10/10/2022','DD/MM/YYYY'),5,200);
INSERT INTO HARVEST(DATEOFHARVEST, SECTOR, NUMBEROFUNITS) VALUES(TO_DATE('9/10/2022','DD/MM/YYYY'),5,87);







DECLARE
    val NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Data Report:');
    FOR I IN (SELECT TABLE_NAME FROM USER_TABLES)
        LOOP
            EXECUTE IMMEDIATE 'SELECT count(*) FROM ' || i.table_name INTO val;
            DBMS_OUTPUT.PUT_LINE(i.table_name || ' ==> ' || val);
        END LOOP;
END;